language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
script:
  - python gwakeonlan.py
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-gi gir1.2-gtk-3.0
install:
  - pip install -r requirements.txt
branches:
  only:
    - master
