dist: bionic
language: python
python:
  - "3.6"
virtualenv:
  system_site_packages: true
script:
  - python -m compileall .
  - flake8 .
  - python setup.py install --optimize=1 --root=build
  - ls -laR build
  - python3 gwakeonlan.py --verbose --autotest
addons:
  apt:
    packages:
    - gir1.2-gtk-3.0
    - gobject-introspection
    - libgirepository1.0-dev
    - gettext
install:
  - pip install -r requirements_travis.txt
services:
  - xvfb
